//Matríz de contenido explorar

function matrixExplorar(nivel){
	if (nivel == 1) {//Emprendedores
		return [
			{"img":"img/emprendedores/img1.png", "name":"Steve Jobs", "history":'"“Visionario, inspirador y brillante”, son las características que describen a Steve Jobs.  <br>Jobs es considerado como “el empresario por excelencia” de nuestra generación.<br>Uno de los aspectos que más impactaron de este empresario es su opinión acerca de los focus groups y las investigaciones de mercados, conceptos que considera como “limitantes de la innovación”. Una vez se le pregunto sobre cuánta investigación había hecho para decidir el lanzamiento del iPad. Su respuesta fue: “Ninguna. No es el trabajo de los consumidores saber qué es lo que quieren. Es difícil que los consumidores te puedan decir qué quieren cuando nunca han visto nada ni remotamente parecido a lo que les ofreces”.<br>Otra importante habilidad de Steve Jobs es la de “seguir su intuición”, una herramienta que uso para detectar tecnologías emergentes y definir el rumbo de Apple. Si deseas conocer más sobre la filosofía de este emprendedor."'},
			{"img":"img/emprendedores/img2.png", "name":"Bill Gates", "history":'"William Henry Gates III (creador de Microsoft), es un empresario, informático y filántropo estadounidense, cofundador de la empresa de software Microsoft junto con Paul Allen. <br>Es uno de los empresarios más extraordinarios de todos los tiempos, gracias a que su revolucionaria mente lo llevó a cambiar el mundo en 2 oportunidades: Primero, ayudó a marcar el comienzo de la revolución del ordenador personal. Ahora está abordando los difíciles retos de la salud mundial y la educación pública, como el filántropo más generoso del mundo.<br>Una vez se le preguntó cuál fue su mejor decisión de negocios, Gates respondió: “La decisión de entrar en el negocio con Paul Allen es, probablemente, la primera de la lista de la lista, y posteriormente la contratación de un amigo... Es importante tener a alguien de su entera confianza, que este totalmente comprometido, que comparta su visión; pero, que también tenga un conjunto de habilidades ligeramente diferentes y que actúe como una especie de control sobre usted"". "'},
			{"img":"img/emprendedores/img3.png", "name":"Jeff Bezos", "history":'"Es el emprendedor que revolucionó las compras a través de Internet. Bezos es el fundador y director ejecutivo de Amazon.com. En 2015 fue el quinto hombre más rico del mundo, y en 2017 alcanzó el primer puesto de la lista Forbes. <br>En 1992, fue vicepresidente senior para The New York hedge fund D.E. Shaw. Él describió su sueño de crear una empresa que vende libros en Internet. Su jefe escuchó atentamente antes de darle un pequeño consejo: “Eso suena como una muy buena idea, pero sería una mejor idea para alguien que no tuviera ya un buen trabajo.”<br>Guiado por su visión y pasión, Bezos decide ignorar el consejo de su jefe y en 1994 pone en marcha su proyecto, pero le tomaría más de 6 meses reportar su primer beneficio trimestral. La paciencia y constancia han sido factores clave para hacer de Amazon una empresa importante y duradera.<br>Una de las prácticas más interesantes de este emprendedor es que al final de cada trimestre se toma un tiempo a solas, para alejarse un poco de la vida empresarial. “Acabo de encerrarme… Es sólo porque con un poco de aislamiento me encuentro con que empiezo a ser más creativo…”."'},
			{"img":"img/emprendedores/img4.png", "name":"Larry Page & Serguéi Brin", "history":'"Larry Page & Serguéi Brin son los creadores del motor de búsquedas que revolucionó el mundo entero. Google es sinónimo de Internet, y para muchos es la interfaz para acceder a un mundo de conocimiento e información único.<br>Page, recuerda la noche en 1996, cuando tenía 23 años y había soñado vívidamente sobre la descarga de toda la Web en los ordenadores. “Cogí un bolígrafo y empecé a escribir, pasé la mitad de esa noche garabateando los detalles y convenciéndome a mí mismo de que iba a funcionar.”<br>Estos dos jóvenes han creado toda una filosofía empresarial, orientada hacia la innovación y el aprovechamiento del potencial de cada miembro de la organización.<br>Actualmente Google ha dejado de ser solo un gran buscador para convertirse en una de las empresas que está definiendo el futuro del Internet y del mundo, gracias al desarrollo de múltiples productos que abarcan desde aplicaciones web y herramientas empresariales, hasta software y conectividad móvil.<br>Las cifras de Google son sorprendentes, y estos dos emprendedores son un claro ejemplo de que para tener éxito hay que soñar con cambiar el mundo. "'},
			{"img":"img/emprendedores/img5.png", "name":"Mark Zuckerberg", "history":'"Zuckerberg, el multimillonario creador de la red social Facebook. <br>Facebook, en solo 8 años desde su fundación, cambió nuestra manera de socializar, de vivir y hasta de hacer negocios. Según algunos, esta red social produjo una de las revoluciones más importantes de la historia, al igual que la produjo la revolución industrial en su momento.<br>“Zuckerberg es un es un genio obsesivo empresarial”, así lo define la revista, y aunque muchos consideren su éxito como un golpe de suerte, la verdad es que este joven empresario ha demostrado grandes habilidades para llevar las riendas de Facebook, la red social con más usuarios en el mundo.<br>Es la personalidad más joven milmillonaria del mundo con 34.200 millones dólares."'},
			{"img":"img/emprendedores/img6.png", "name":"Warren Edward Buffett", "history":'"Warren Edward Buffett es un inversor y empresario estadounidense, considerado uno de los más grandes inversores en el mundo, además de ser el mayor accionista y Director Ejecutivo de Berkshire Hathaway. En 2017 ocupa la segunda posición en la lista de hombres más ricos del mundo elaborada por la revista Forbes, por detrás de Bill Gates y delante del fundador de Amazon, Jeff Bezos con una fortuna estimada de 75, 600 millones de dólares.<br>Una de sus grandes frases es:<br>Dale a tu mente algo de claridad. <br>""Insisto en pasar mucho tiempo, casi todos los días, sentado y pensando. Esto no es común en los negocios americanos. Yo leo y pienso, así que leo más de lo que pienso, por lo que tomo menos decisiones impulsivas que otras personas en los negocios. Lo hago porque me gusta este tipo de vida""."'},
			{"img":"img/emprendedores/img7.png", "name":"Sam Walton", "history":'"Sam es el fundador de Wal-Mart, la tienda minorista más grande de Estados Unidos y una de las empresas más grandes del mundo.<br>La piedra angular del éxito de su empresa, en última instancia, es poner en venta productos al menor precio posible, algo que él era capaz de hacer al echar a un lado los intermediarios y dirigirse directamente el regateo con los fabricantes para bajar los costos. La idea de “comprar bajo, pila en alto, y vender barato” se convirtió en un modelo de negocio sostenible en gran medida debido a Walton.<br>Él compartió los datos en tiempo real con los proveedores para crear alianzas que permitieron a Wal-Mart de ejercer una importante presión sobre los fabricantes para mejorar su productividad y ser cada vez más eficientes. <br>Su regla número 1 para el éxito fue: Comprométase a triunfar y sea entusiasta.<br>Walton estaba absolutamente decidido a hacer lo que fuera necesario para realizar sus sueños. Solía ir a trabajar a las 4:00 AM para poder revisar los informes de venta del día anterior y pensar un poco antes de que llegaran los demás ejecutivos. "'},
			{"img":"img/emprendedores/img8.png", "name":"Richard Branson", "history":'"Branson es el creador de la marca Virgen, que engloba a más de 360 empresas del Virgin Group.<br>Su historia como emprendedor comienza a los 16 años, cuando publicó una revista llamada Student. A los 20 creó un registro por correo para empresas, y tan solo dos años más tarde abrió la cadena de Virgin Records.<br>El gran secreto de Branson es que sus padres le enseñaron a aprender por medio de la reflexión.<br>Cuando Richard Branson era niño, cada vez que decía algo desagradable acerca de cualquier otra persona, sus padres lo mandaban a su habitación para que se mirara en el espejo. Tenía que mirar su reflejo mientras pensaba en lo que había dicho. La intención de sus padres era tratar de hacerle comprender que el ser ruin o negativo sobre otras personas era desagradable y se reflejaba negativamente en él.<br>La lección tuvo efecto: ""Mirarme en el espejo durante cinco minutos no era muy divertido, así que dejé de criticar a la gente”."'},
			{"img":"img/emprendedores/img9.png", "name":"Amancio Ortega", "history":'"Es un empresario español dedicado al sector textil. Es fundador, junto con su exesposa Rosalía Mera, y expresidente del grupo empresarial textil Inditex, cargo en el que le sucedió Pablo Isla, y de la cadena de tiendas de ropa más conocida del grupo: Zara.<br>Según Forbes la clave de éxito de Zara es “Un modelo de gestión basado en la flexibilidad y la innovación, atento siempre no solo a las últimas tendencias del mundo de la moda sino a las necesidades y demandas de sus compradores. Desde el principio Ortega tuvo claro que si quería tener sus tiendas llenas, debía ofrecer a esos clientes lo que ellos estaban buscando y a un precio accesible”.<br>Actualmente cuenta con tiendas repartidas por todo el mundo, con una fortuna de más de 70.000 euros."'},
			{"img":"img/emprendedores/img10.png", "name":"Thomas Alva Edison", "history":'"Fue un empresario y un prolífico inventor estadounidense que patentó más de mil inventos y contribuyó a proporcionar, tanto a Estados Unidos como a Europa, los perfiles tecnológicos del mundo contemporáneo: las industrias eléctricas, un sistema telefónico viable, el fonógrafo, las películas, etc.<br>En 1889 Edison inventó el kinetoscopio. En 1913 sincronizó el kinetoscopio con el fonógrafo para producir la primera película sonora de la historia del cine. Otro de sus inventos fue el micrófono de carbón, que mejoró enormemente la calidad de transmisión de la voz a través del teléfono. <br>Entre otros de los inventos de Edison destacan el telégrafo impresor, el telégrafo cuádruplex (1874), el micrófono de carbón (que mejoraba el desarrollado por A. G. Bell, inventor de la telefonía), el fonógrafo(1877), una máquina de dictado, el antecedente más directo del cine de los hermanos Lumière (el kinetoscopio, 1889), las pilas alcalinas(acumulador de ferroníquel, 1883) y diversos tipos de cemento y de hormigón.<br>–  “El Genio es un 1% de Inspiración y 99% de Transpiración”<br>–  “No Fracasé, soló descubrí 999 maneras de cómo no hacer una bombilla.”<br>–  “Los que aseguran que es imposible, no deberían interrumpir a los que lo estamos Intentando.”<br>–  “Quien no se resuelve a cultivar el hábito de pensar, se pierde del mayor placer de la vida.” Thomas Alva Edison"'},
			{"img":"img/emprendedores/img11.png", "name":"Elon Musk", "history":'"Elon Musk es un físico sudafricano que comenzó su vida intentando crear algo de importancia y que dejara marca en el mundo.<br>Incansable desde pequeño, este sudafricano decidió trasladarse a Estados Unidos para lanzar su carrera. La creación de la empresa Zip2 le llevaría a gestionar más de 200 webs para fundar años más tarde X.com, una empresa de seguridad financiera y que derivaría en PayPal.<br>Musk es conocido por ser el cofundador de PayPal, Tesla Motors, SpaceX, Hyperloop, SolarCity, The Boring Company y OpenAI. Actualmente, es el director general de SpaceX, el director general de Tesla Motors, presidente de SolarCity y copresidente de OpenAI."'},
			{"img":"img/emprendedores/img12.png", "name":"Henry Ford", "history":'"Fue el fundador de la compañía Ford Motor Company y padre de las cadenas de producción modernas utilizadas para la producción en masa. Su iniciativa y revolucionarias ideas lo llevaron a fundar una de las marcas de coches más famosas del mundo.<br>Su infancia como aprendiz de maquinista le llevó a ser contratado por una compañía de máquinas de vapor y posteriormente como ingeniero en la compañía Edison.<br>Tras acumular una gran experiencia en el mundo de las máquinas, crearía Ford Motor Company. Sus coches pasarían a la historia gracias a sus revolucionarios diseños (como poner el volante a la izquierda). "'},
			{"img":"img/emprendedores/img13.png", "name":"Howard Schultz", "history":'"Empresario estadounidense, presidente y consejero delegado de Starbucks Coffee Company, una franquicia con una particular filosofía de los negocios que cuenta con más de 10.000 establecimientos en todo el mundo.<br>Su incorporación como director de marketing revolucionó la filosofía de la famosa cafetería: reprodujo los cappuccinos italianos en Starbucks para comenzar a llevar las riendas de la empresa.<br>Schultz sentó las bases de lo que al día de hoy significa esta cadena, en la que buscaba un “ambiente en el que la intimidad de la relación con el espacio y la experiencia del café pudiera cobrar vida”."'},
			{"img":"img/emprendedores/img14.png", "name":"Walt Disney", "history":'"Fue un productor, director, guionista y animador estadounidense. Figura capital de la historia del cine de animación infantil, está considerado un icono internacional gracias a sus importantes contribuciones a la industria del entretenimiento durante gran parte del siglo XX, famoso por personajes como el Pato Donald o Mickey Mouse.<br>Disney es la persona con más premios Oscar en la historia del cine. Todo comenzó con su pasión por el dibujo y la historieta, algo que le llevó a trabajar en un estudio de arte. Pero no sería hasta años más tarde cuando crearía Laugh-O-Gram Films, Inc., empresa dedicada a realizar cortometrajes para niños, donde crearía Alicia en el País de las Maravillas.<br>Años más tarde, una productora de Hollywood se interesó por su película y lo contrato para hacer más cintas.<br>Su éxito llegó con la creación de Mickey Mouse, que hizo que toda la prensa quedara rendida a sus pies. El personaje llegó a ser galardonado por la Sociedad de Naciones como Símbolo Internacional de Buena Voluntad.<br>A raíz de ese momento, nacerían nuevos personajes como Goofy o el Pato Donald, y con ellos, películas y el reconocimiento internacional del que hoy goza."'},
			{"img":"img/emprendedores/img15.png", "name":"Steve Wozniak", "history":'Stephen (o Stephan) Gary "Steve" Wozniak, también conocido como "Woz", es un ingeniero, filántropo, empresario e inventor estadounidense, cofundador de la compañía Apple. Se le considera uno de los padres de la revolución de las computadoras, habiendo contribuido significativamente a la invención de una computadora personal (PC, personal computer) en los años 1970. Wozniak ayudó a fundar Apple Computer (ahora Apple Inc.) junto con Steve Jobs en 1976. A mediados de la década de 1970, creó la computadora Apple I y Apple II. Esta última ganó gran popularidad y con el tiempo, se convirtió en la computadora más vendida en los años 1970 y principios de 1980.'},
			{"img":"img/emprendedores/img16.png", "name":"Lawrence J. Ellison", "history":'"Lawrence Joseph Ellison, conocido como Larry Ellison, es el fundador de Oracle donde fue Director Ejecutivo de 1977 hasta 2015. Es uno de los multimillonarios más conocidos y ocupa el puesto número 6 entre las mayores fortunas personales del mundo según la revista Forbes, después de Mark Zuckerberg.<br>Actualmente, Oracle se trata de la empresa número uno en el sistema de gestión de bases de datos relacionales con una cuota de mercado."'},
			{"img":"img/emprendedores/img17.png", "name":"Ray Kroc", "history":'"Raymond Albert Kroc, más conocido como Ray Kroc, fue un empresario, comerciante e inversionista estadounidense, famoso por impulsar la empresa McDonald´s, después de adquirirla a los hermanos Dick y Mac McDonald en 1961, 15 años después de su fundación. Pese a no ser el creador, fue el responsable de la internacionalización y expansión de la misma.<br>Antes de su éxito en la cadena de comida rápida, Ray había intentado llevar a cabo otro tipo de negocios como por ejemplo la comercialización de Multimixer, una máquina que podía hacer hasta cinco malteadas a la vez."'},
			{"img":"img/emprendedores/img18.png", "name":"Soichiro Honda", "history":'"Fue un ingeniero y empresario industrial japonés, fundador de la multinacional Honda Motors (en 1948).<br>Soichiro Honda, recién graduado, acudió a una entrevista de trabajo para trabajar en Toyota. Tras realizarla, le dijeron que sus características no cuadraban con la empresa, y que por tanto, no iba a acceder al puesto de trabajo.<br>Este obstáculo supuso para su vida un antes y un después. Decidió crear por su cuenta la empresa que el día de hoy se conoce como Honda, una de los mayores fabricantes de motos y coches de todo el mundo."'},
			{"img":"img/emprendedores/img19.png", "name":"Chris Gardner", "history":'"Christopher Paul Gardner es un millonario emprendedor, conferencista y filántropo estadounidense.<br>Luchó a favor de las personas sin hogar en Estados Unidos mientras criaba a su hijo Christopher a comienzos de la década de 1980. Reside en Nueva York y Chicago.<br>La aventura de Gardner de ser un padre sin casa hasta llegar a ser multimillonario se ha retratado en una película que se estrenó en Estados Unidos a finales de 2006, titulada En busca de la felicidad, en la que el actor que encarna a Chris es Will Smith. La película tiene como guión una adaptación del libro de las memorias de Gardner con el mismo título que fue publicado en el mismo año."'},
			{"img":"img/emprendedores/img20.png", "name":"Muhammad Yunus", "history":'"Es un emprendedor social, banquero, economista y líder social bangladesí condecorado con el Premio Nobel de la Paz por desarrollar el Banco Grameen y ser el desarrollador de los conceptos de microcrédito y microfinanzas. Estos créditos son otorgados a emprendedores que son muy pobres para calificar a un crédito en un banco tradicional. En 2006, Yunus y el Banco Grameen fueron condecorados con el Premio Nobel de la Paz ""por sus esfuerzos para incentivar el desarrollo social y económico desde abajo"". El Comité Noruego Nobel hizo notar que ""la paz duradera no puede ser alcanzada a menos que grandes grupos de la población encuentren formas en las que puedan salir de la pobreza"" y que ""a través de culturas y civilizaciones, Yunus y el Banco Grameen han demostrado que hasta los más pobres de entre los pobres pueden trabajar para su propio desarrollo. "'},
		];
	}
	if (nivel == 2) {//Tips
		return [
			{"sentence":"Ten Coraje", "img":"img/tips/img1.png", "detail":'“Todos tus sueños pueden hacerse realidad si tienes el coraje de perseguirlos”. Walt Disney'},
			{"sentence":"Aprende de los errores", "img":"img/tips/img1.png", "detail":'"Está bien celebrar el éxito, pero es más importante prestar atención a las lecciones del fracaso". Bill Gates.'},
			{"sentence":"Toma riesgos", "img":"img/tips/img1.png", "detail":'"El riesgo más grande es no tomar ninguno. En un mundo que está cambiando tan rápido, la única estrategia que está garantizada a fracasar es no tomar riesgos". Mark Zuckerberg.'},
			{"sentence":"Persiste", "img":"img/tips/img1.png", "detail":'"La persistencia es muy importante. No debes renunciar al menos que te veas obligado a renunciar". Elon Musk'},
			{"sentence":"Sueña", "img":"img/tips/img1.png", "detail":'"No duermas para descansar, duerme para soñar. Porque los sueños están para cumplirse".-Walt Disney.'},
			{"sentence":"Celebra siempre", "img":"img/tips/img1.png", "detail":'"Celebra tu éxito. Encuentra algo de humor en tus fracasos". Sam Walton.'},
			{"sentence":"Diviértete", "img":"img/tips/img1.png", "detail":'"Debes hacer cosas que realmente sean importantes, pero también debes divertirte, porque sino, no tendrás éxito". Larry Page'},
			{"sentence":"Nunca dejes que la timidez conquiste tu mente", "img":"img/tips/img1.png", "detail":'"Si quieres hacer algo grande en tu vida, debes recordar que la timidez está solo en la mente. Si piensas con timidez, tus actos serán similares. Pero si piensas con seguridad, actuaras de la misma forma". Bill Gates'},
			{"sentence":"Trabaja en equipo", "img":"img/tips/img1.png", "detail":'"Reunirse es un comienzo, permanecer juntos es el progreso y trabajar juntos es el éxito". Henry Ford'},
			{"sentence":"No te rindas", "img":"img/tips/img1.png", "detail":'“El fracaso derrota a los perdedores e inspira a los ganadores”. Robert Kiyosaki'},
			{"sentence":"Estudia duro", "img":"img/tips/img1.png", "detail":'"No estudies duro para encontrar una buena compañía para la cual trabajar, estudia duro para que encuentres una buena compañía que comprar". Robert Kiyosaki'},
			{"sentence":"Atrévete", "img":"img/tips/img1.png", "detail":'“La manera de empezar es dejar de hablar y empezar a hacer”. Walt Disney'},
			{"sentence":"Sé un ganador", "img":"img/tips/img1.png", "detail":'“Los ganadores nunca abandonan y los que abandonan nunca ganan”. Vince Lombardi'},
			{"sentence":"Haz que las cosas ocurran", "img":"img/tips/img1.png", "detail":' "Tan solo hay tres grupos de personas: los que hacen que las cosas pasen, los que miran las cosas que pasan y los que preguntan qué pasó". Nicholas Murray Butler.'},
			{"sentence":"No pierdas el entusiasmo", "img":"img/tips/img1.png", "detail":'"El éxito es la capacidad de ir de fracaso en fracaso sin perder entusiasmo". Winston Churchill.'},
			{"sentence":"Actúa", "img":"img/tips/img1.png", "detail":'"La visión sin la ejecución, solo es una alucinación". Henry Ford'},
			{"sentence":"Lucha por tus sueños", "img":"img/tips/img1.png", "detail":'"Si tú no trabajas por tus sueños, alguien te contratará para que trabajes por los suyos". Steve Jobs'},
			{"sentence":"Enfócate", "img":"img/tips/img1.png", "detail":'"Si quieres tener éxito, debes aprender a enfocarte". Robert Kiyosaki'},
			{"sentence":"Cree en ti mismo", "img":"img/tips/img1.png", "detail":'Una persona sin autoconfianza, no puede desarrollarse como emprendedora. Toda actividad que deba partir de ti, empieza dentro de ti mismo.'},
			{"sentence":"Vence tus miedos", "img":"img/tips/img1.png", "detail":'"Las personas exitosas aprenden a sobreponerse a sus miedos, en lugar de dejar que sus miedos manejen su vida." Robert Kiyosaki.'},
			{"sentence":"Debes buscar el éxito", "img":"img/tips/img1.png", "detail":'"Si deseas tener éxito, debes buscar nuevos caminos, en lugar de recorrer los caminos tradicionales del éxito, que todos conocen." John D. Rockefeller.'},
			{"sentence":"Crece", "img":"img/tips/img1.png", "detail":'"El crecimiento constante es el mejor mecanismo de supervivencia." Amancio Ortega'},
			{"sentence":"Aprovecha las oportunidades", "img":"img/tips/img1.png", "detail":'"Las oportunidades grandes, nacen de haber sabido aprovechar las pequeñas." Bill Gates'},
			{"sentence":"La vida es contracorriente", "img":"img/tips/img1.png", "detail":'"Cuando todo parece que va en contra tuya, recuerda que un avión despega siempre en contra del viento, no a favor" Henry Ford'},
			{"sentence":"Sigue tu intuición", "img":"img/tips/img1.png", "detail":'"Haz las cosas que te gusten, aunque de momento no sepas por qué te atraen. No te cortes las alas SIGUE TU INTUICIÓN." Steve Jobs'},
			{"sentence":"Haz lo que amas", "img":"img/tips/img1.png", "detail":'"No hay plan B para la pasión, haz lo que amas y el éxito llegará". Chris Gardner'},
			{"sentence":"Innova", "img":"img/tips/img1.png", "detail":'"Si buscas resultados distintos, no hagas siempre lo mismo". Albert Einstein'},
			{"sentence":"Nunca", "img":"img/tips/img1.png", "detail":'"Nunca darse por vencido. Nunca Aparentar. Nunca mantenerse inmóvil. Nunca aferrarse al pasado. Nunca dejar de soñar. Steve Jobs"'},
			{"sentence":"Sé feliz", "img":"img/tips/img1.png", "detail":'"Casi todas las personas son tan felices como se deciden serlo." Abraham Lincoln.'},
			{"sentence":"Trabaja", "img":"img/tips/img1.png", "detail":'"Trabaja duro, diviértete, haz historia." Jeff Bezos.'},
			{"sentence":"Desarrolla un espíritu crítico, empezando por ti mismo.", "img":"img/tips/img1.png", "detail":' La apatía y el conformismo con uno mismo y con lo establecido son dos de los principales enemigos del emprendimiento.'},
			{"sentence":"Ambiciona objetivos ", "img":"img/tips/img1.png", "detail":'Valora periódicamente si tus acciones te están acercando o alejando de ellos. Cualquier objetivo que te propongas y te motive lo suficiente es válido, plenamente válido. Visiónalos y acércate cada día más a ellos.'},
			{"sentence":"Que tus ambiciones sean reales y lógicas", "img":"img/tips/img1.png", "detail":'Puede ser muy grandilocuente querer conquistar el mundo o abolir el hambre en África, pero sé razonable con tu micro mundo... Debes tener pequeños objetivos a corto plazo.'},
			{"sentence":"Desarrolla tus cualidades creativas. ", "img":"img/tips/img1.png", "detail":'El mayor enemigo de la creatividad es uno mismo y sus "certezas de que no es creativo". Todos podemos ser creativos en mayor o menor medida. '},
			{"sentence":"Elije ser piloto", "img":"img/tips/img1.png", "detail":'Las personas se pueden dividir en dos grupos: los que pilotan su existencia y los que se dejan flotar y acompañan a la gran masa según sople el viento. Toma tus propias decisiones, aunque te separen del camino de las personas más cercanas.'},
			{"sentence":"Dedica tiempo a pensar", "img":"img/tips/img1.png", "detail":'“Quien no se resuelve a cultivar el hábito de pensar, se pierde del mayor placer de la vida.” Thomas Alva Edison'},
			{"sentence":"Los errores son oportunidades", "img":"img/tips/img1.png", "detail":'“Los que aseguran que es imposible, no deberían interrumpir a los que lo estamos Intentando.” Thomas Alva Edison'},
			{"sentence":"Valora a los demás de la misma forma en la que te gustaría ser valorado.", "img":"img/tips/img1.png", "detail":'La "meritocracia" es el ecosistema lógico más beneficioso para cualquier persona emprendedora. Siguiendo la misma regla de tres, para ser tratado así, deberías valorar del mismo modo a los demás.'},
		];
	}
	if (nivel == 3) {//Pasos
		return [
			{"step":"siente", "img":"img/pasos/img1.png", "detail":'<b>¿Qué es lo que no te gusta de tu entorno?</b><br><b>¿Qué es lo que te gustaría cambiar?</b><br>En esta etapa debes comportarte como un detective para comprender mejor la situación de tu escuela, comunidad o país, que te gustaría mejorar o cambiar. <br>La clave en este proceso es COMPRENDER.<br><br>Ahora debes organizarte y hacer lo siguiente:<br>• Organiza la información.<br>• Identifica el objetivo de acción.<br>• Elige un objetivo. <br>• Comprende.<br>• Sintetiza lo aprendido.<br>• Genera un reto.'},
			{"step":"piensa", "img":"img/pasos/img2.png", "detail":'<b>¿Cómo lo cambiarías y qué necesitas para hacerlo?</b><br><br>Imagina, piensa cómo resolverías el reto o problema identificado en tu escuela, comunidad o país. Aquí la clave es EXPLORAR POSIBILIDADES, proponiendo muchas posibles soluciones.<br><br>Realiza lo siguiente:<br>• Propone muchas ideas/soluciones.<br>• Elige las mejores.<br>• Define tu propuesta.<br>• Diseña un prototipo.<br>• Crea un plan de acción.'},
			{"step":"crea", "img":"img/pasos/img3.png", "detail":'<b>Llegó el momento de poner en práctica la solución que diseñaste.</b><br><br> Involucra a los padres de familia, maestros, directores, miembros de la comunidad y todo a quien consideres necesario. <br><br>La clave aquí es la ACCIÓN.<br>¡Adelante tú puedes!'},
			{"step":"comparte", "img":"img/pasos/img4.png", "detail":'<b>Invita a toda tu comunidad a participar y diseñar el cambio.</b><br><br> En esta parte clave es INSPIRAR y contagiar a otros con el ¡Yo puedo! El proceso comienza viendo lo que han hecho otros y finaliza compartiendo lo realizado.<br><br>• Presenta tu proyecto.<br>• Difunde tu proyecto."'},
			{"step":"reflexiona", "img":"img/pasos/img5.png", "detail":'<b>La clave es "Reflexionar para crecer" mirando al pasado.</b><br><br>Evalúa lo que has vivido y mirando hacia el futuro piensa en lo que puedes mejorar, en qué puedes crecer.<br><br>• Reflexiona sobre tu experiencia<br>• Haz que tu proyecto evolucione'},
		];
	}

}
